# Generated by Django 5.2.4 on 2025-07-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_x', models.CharField(default='Player X', max_length=50)),
                ('player_o', models.CharField(default='Player O', max_length=50)),
                ('winner', models.CharField(choices=[('X', 'X'), ('O', 'O'), ('Tie', 'Tie')], max_length=10)),
                ('board', models.JSONField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
